// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Hangman, HangmanData, HangmanTableId } from "./tables/Hangman.sol";
import { UsedLetters, UsedLettersTableId } from "./tables/UsedLetters.sol";
import { KnownLetters, KnownLettersTableId } from "./tables/KnownLetters.sol";
