// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IHangmanSystem {
  function setGame(uint32 _maxAttempts) external returns (bytes32 id);

  function guessLetter(bytes1 letter) external returns (uint);

  function guessWord(bytes memory word) external;

  function getKnownLetters() external returns (bytes1[] memory);

  function getUsedLetters() external view returns (bytes1[] memory);

  function getSolutionLength(bytes32 gameId) external view returns (uint);
}
